"""Change integer columns to enum types for role, meeting status/type, room status

Revision ID: 5bbfe51a1cab
Revises: 0e4292a4b8dc
Create Date: 2026-04-21 08:48:13.284319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bbfe51a1cab'
down_revision: Union[str, Sequence[str], None] = '0e4292a4b8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types using raw SQL
    op.execute("CREATE TYPE meetingstatus AS ENUM ('CANCELED', 'SCHEDULED', 'COMPLETED')")
    op.execute("CREATE TYPE meetingtype AS ENUM ('IN_PERSON', 'ONLINE', 'HYBRID')")
    op.execute("CREATE TYPE roomstatus AS ENUM ('UNAVAILABLE', 'AVAILABLE')")
    op.execute("CREATE TYPE userrole AS ENUM ('USER', 'ADMIN')")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('CANCELED', 'SCHEDULED', 'COMPLETED', name='meetingstatus'),
               existing_nullable=True,
               postgresql_using="CASE status WHEN 0 THEN 'CANCELED' WHEN 1 THEN 'SCHEDULED' WHEN 2 THEN 'COMPLETED' END::meetingstatus")
    op.alter_column('meetings', 'type',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', name='meetingtype'),
               existing_nullable=True,
               postgresql_using="CASE type WHEN 0 THEN 'IN_PERSON' WHEN 1 THEN 'ONLINE' WHEN 2 THEN 'HYBRID' END::meetingtype")
    op.alter_column('rooms', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('UNAVAILABLE', 'AVAILABLE', name='roomstatus'),
               existing_nullable=True,
               postgresql_using="CASE status WHEN 0 THEN 'UNAVAILABLE' WHEN 1 THEN 'AVAILABLE' END::roomstatus")
    op.alter_column('users', 'role',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('USER', 'ADMIN', name='userrole'),
               existing_nullable=True,
               postgresql_using="CASE role WHEN 0 THEN 'USER' WHEN 1 THEN 'ADMIN' END::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='userrole'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rooms', 'status',
               existing_type=sa.Enum('UNAVAILABLE', 'AVAILABLE', name='roomstatus'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('meetings', 'type',
               existing_type=sa.Enum('IN_PERSON', 'ONLINE', 'HYBRID', name='meetingtype'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('meetings', 'status',
               existing_type=sa.Enum('CANCELED', 'SCHEDULED', 'COMPLETED', name='meetingstatus'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    
    # Drop enum types
    op.execute("DROP TYPE userrole")
    op.execute("DROP TYPE roomstatus")
    op.execute("DROP TYPE meetingtype")
    op.execute("DROP TYPE meetingstatus")
    # ### end Alembic commands ###
